#include<iostream.h>
#include<string.h>
main()
{
char hari;
cout <<"Masukkan Kode Hari (A-G) :";
cin>>hari;
if(hari=='a'||hari=='A')
{
cout<<"Senin";}
else if(hari=='b'||hari=='b')
{
cout<<"Selasa";}
else if (hari=='c'|| hari=='c')
{
cout<<"Rabu";]
else if (hari=='d'||hari=='D')
{
cot<<"kamis";}
else if (hari=='e'||hari=='E')
{
cout<<"jumat";}
else if (hari=='g'||hari=='G')
{
cout<<"Sabtu";}
else if (hari=='g'||hari=='G')
{
cout<<"Minggu";}
else
cout<<"Maaf kode hari yang anda masukkan salah";
return0;
}
